In [13]:
import numpy as np
import imageio


In [14]:
def maskOfColor(color, img):
    red, green, blue = img[:,:,0], img[:,:,1], img[:,:,2]
    mask = (red == color[0]) & (green == color[1]) & (blue == color[2])
    return mask

In [15]:
def createTestImage(name):
    red = np.full((25,75, 3), 0, 'uint8')
    blue = np.full((25,75,3), 100, 'uint8')
    yellow = np.full((25,75,3), 256, 'uint8')
    sample = np.vstack((red, blue, yellow))
    imageio.imwrite(name, sample)
    return sample

In [16]:
sample = createTestImage("testImage.jpg")
color = [200,200,200]
x = maskOfColor(color, sample)
print sample[x]
imageio.imwrite("maskedBool.jpg", x)

[[200 200 200]
 [200 200 200]
 [200 200 200]
 ..., 
 [200 200 200]
 [200 200 200]
 [200 200 200]]
