In [7]:
from scipy import ndimage, misc, stats
import numpy as np
import os

In [ ]:
def mkdirsafe (newpath):
    """make directory if it doesn't already exist"""
    if not os.path.exists(newpath): os.makedirs(newpath)

In [8]:
def filterdirectory(path,extension):
    """return list of files under the directory given by the path that ends with the extension"""
    files = [file for file in os.listdir(path) if file.lower().endswith(extension) and file[0] !='.']
    return files

In [33]:
path_to_images = "C:/Users/dfpena/Desktop/Better_Images/TestBed/593/"

directory = filterdirectory(path_to_images,".jpg")
print(directory)

for picPath in directory:
    picArr = ndimage.imread(picPath)
    print(picArr.shape)
    for i in range(0,picArr.shape[0]):
        whiteMask = (picArr[i] == [255,255,255])
        picArr[whiteMask] = 0
    newPicPath = "cropped/" + picPath.split(".")[0] + "_white.jpg" 
    mkdirsafe('cropped')
    misc.imsave(newPicPath, picArr)

['362_593_1_2_ps.jpg', '370_593_1_4_ps.jpg', '374_593_1_5.jpg', '382_593_1_7.jpg', '386_593_1_8.jpg', '390_593_1_9.jpg', '394_593_1_10.jpg', '398_593_1_11.jpg', '406_593_2_1.jpg']
(5064, 7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(782

(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)


(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)


(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)
(7824, 3)


NameError: name 'mkdirsafe' is not defined

In [66]:
sampleImage = np.array([[[255, 255, 255], [255, 255, 255], [255, 255, 255]],
               [[125, 255, 128], [128, 0, 128], [128, 128, 128]],
               [[255, 255, 255], [255, 255, 255], [0, 0, 0]]])
print(sampleImage)
print(sampleImage[:, :,0])
# print(sampleImage[:,:,0])
# print(sampleImage == sampleImage[:,:,0])
# wbMask = np.all(sampleImage == sampleImage[:,:,0], axis = 2)
# wbMask

[[[255 255 255]
  [255 255 255]
  [255 255 255]]

 [[125 255 128]
  [128   0 128]
  [128 128 128]]

 [[255 255 255]
  [255 255 255]
  [  0   0   0]]]
[[255 255 255]
 [125 128 128]
 [255 255   0]]
